# strings are immutsble
a = "BRuce____ _"
print(len(a))
print(a.upper())
print(a.lower())
print(a.rstrip("_"))
print(a.replace("BRuce","Wayne"))
print(a.split(" "))
print(a.capitalize())
print(a.center(50))
print(len(a.center(50)))
print(a.count("BRuce"))
print(a.endswith("___"))
print(a.endswith("___",4,8))
print(a.find("BR"))
print(a.index("BR"))
print(a.isalnum())
print(a.isalpha())
print(a.islower())
print(a.isprintable())
print(a.isspace())
print(a.istitle())
print(a.swapcase())
print(a.title())